name: GitHub Actions Analysis

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - .github/matchers/*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/*
      - .github/matchers/*

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

permissions: {}

jobs:
  zizmor:
    name: Security Analysis
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
      contents: read # Only needed for private repos. Needed to clone the repo.
      actions: read # Only needed for private repos. Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@0dce2577a4760a2749d8cfb7a84b7d5585ebcb7d # v0.5.0
        with:
          inputs: .github/workflows
          persona: auditor
  actionlint:
    name: Actionlint
    runs-on: ubuntu-slim
    permissions:
      contents: read # Only needed for private repos. Needed to clone the repo.
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Add Matcher
        run: echo "::add-matcher::.github/matchers/actionlint.json"
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
