name: GitHub Actions Analysis

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - .github/formatters/*
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/*
      - .github/formatters/*
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/garbee/mtgjson-cli-devcontainer@sha256:4ad225a9b00fb4f4923489d02670ec73b968be7eac31c16ec5be5157ceae604c
    permissions:
      security-events: write # Required for upload-sarif to upload SARIF files.
      contents: read # Only needed for private repos. Needed to clone the repo.
      actions: read # Only needed for private repos. Needed for upload-sarif to read workflow run info.
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run zizmor
        run: zizmor --format=sarif --persona auditor . > zizmor.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@6bc82e05fd0ea64601dd4b465378bbcf57de0314 # v4.32.1
        with:
          sarif_file: zizmor.sarif
          category: zizmor
  actionlint:
    name: Actionlint
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/garbee/mtgjson-cli-devcontainer@sha256:4ad225a9b00fb4f4923489d02670ec73b968be7eac31c16ec5be5157ceae604c
    permissions:
      contents: read # Only needed for private repos. Needed to clone the repo.
      actions: read # Only needed for private repos. Needed for upload-sarif to read workflow run info.
      security-events: write # Required for upload-sarif to upload SARIF files.
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Check workflow files
        run: actionlint -format "$(cat .github/formatters/actionlint-sarif.gotmpl)" .github/workflows/*.yml > actionlint.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@6bc82e05fd0ea64601dd4b465378bbcf57de0314 # v4.32.1
        with:
          sarif_file: actionlint.sarif
          category: actionlint
